---
# Tasks for Apache

- name: Install Apache
  yum:
    name: httpd
    state: present

- name: Ensure Apache service is running and enabled
  service:
    name: httpd
    state: started
    enabled: yes
  notify:
    - restart Apache

- name: Set firewall rule for Apache
  firewalld:
    service: http
    permanent: yes
    state: enabled
    immediate: yes

- name: Ensure Apache starts on boot
  systemd:
    name: httpd
    enabled: yes
