---
- name:  Configure Apache
  hosts: all
  become: true
  roles:
    - Apache
    
- name: create /opt/www
  hosts: all
  become: true

  tasks:
  - name: Create /opt/www directory
    file:
       path: /opt/www
       state: directory
       owner: apache
       group: apache
       mode: '0755'

- name: Apache html root
  hosts: all
  become: true
  vars:
    apache_path: /opt/www

  tasks: 
    - name: change directory
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^DocumentRoot.*'
        line: 'DocumentRoot "{{ apache_path }}"'

- name: Set SELinux privileges
  hosts: all
  become: true

  tasks:
    - name: Set SELinux context
      selinux:
        seuser: system_u
        serole: object_r
        setype: httpd_sys_content_t
        state: file
        target: /opt/www


 
