##MySQL dumping
- name: Schedule MySQL database dump
  hosts: all
  become: true

  tasks:
    - name: Create backup directory
      file:
        path: /backup/mysql
        state: directory
        mode: '0700'

    - name: Dump MySQL database
      mysql_db:
        state: dump
        name: dBB
        login_host: localhost
        login_user: db:conferencia
        login_password: redhat
        target: /backup/mysql/dBB.sql
      register: dump_result

    - name: Schedule weekly database dump
      cron:
        name: "Weekly database dump"
        minute: "0"
        hour: "23"
        weekday: "0"
        job: "cd /backup/mysql && mysqldump -h localhost -u db:conferencia -p'redhat' dBB > dBB.sql"
      when: dump_result.changed

