---
- name: Install MySQL
  hosts: all
  become: true

  tasks:
    - name: Install MySQL package
      yum:
        name: mysql-server
        state: present
    
    - name: Install mysql
      yum: 
        name: mysql
        state: present

    - name: Install pip
      yum:
        name: python3-pip
        state: present

    - name: Install MySQL-python package
      pip:
        name: MySQL-python
        state: present
        executable: pip3
        extra_args: --user

    - name: Start MySQL service
      service:
        name: mysqld
        state: started
        enabled: yes
      notify:
        - restart mysql

  handlers:
    - name: restart mysql
      service:
        name: mysqld
        state: restarted
